import mongoose from 'mongoose';

export const ADMIN_ROLE = 'SUPER_ADMIN';
export const USER_ROLE = 'NORMAL_USER';

export const INIT_PERMISSIONS = [
  // PERMISSIONS MODULE
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[PERMISSIONS] Create a new permission',
    apiPath: '/api/v1/permissions',
    method: 'POST',
    module: 'PERMISSIONS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[PERMISSIONS] Get all permissions',
    apiPath: '/api/v1/permissions',
    method: 'GET',
    module: 'PERMISSIONS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[PERMISSIONS] Get a permission by id',
    apiPath: '/api/v1/permissions/:id',
    method: 'GET',
    module: 'PERMISSIONS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[PERMISSIONS] Update a permission',
    apiPath: '/api/v1/permissions/:id',
    method: 'PATCH',
    module: 'PERMISSIONS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[PERMISSIONS] Delete a permission',
    apiPath: '/api/v1/permissions/:id',
    method: 'DELETE',
    module: 'PERMISSIONS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  // COMPANIES MODULE
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[COMPANIES] Get company with paginate',
    apiPath: '/api/v1/companies',
    method: 'GET',
    module: 'COMPANIES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[COMPANIES] Create a new company',
    apiPath: '/api/v1/companies',
    method: 'POST',
    module: 'COMPANIES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[COMPANIES] Get a company by id',
    apiPath: '/api/v1/companies/:id',
    method: 'GET',
    module: 'COMPANIES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[COMPANIES] Update a company',
    apiPath: '/api/v1/companies/:id',
    method: 'PATCH',
    module: 'COMPANIES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[COMPANIES] Delete a company',
    apiPath: '/api/v1/companies/:id',
    method: 'DELETE',
    module: 'COMPANIES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  // USERS MODULE
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[USERS] Create a new user',
    apiPath: '/api/v1/users',
    method: 'POST',
    module: 'USERS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[USERS] Get all users with pagination',
    apiPath: '/api/v1/users',
    method: 'GET',
    module: 'USERS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[USERS] Get a user by id',
    apiPath: '/api/v1/users/:id',
    method: 'GET',
    module: 'USERS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[USERS] Update a user',
    apiPath: '/api/v1/users',
    method: 'PATCH',
    module: 'USERS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[USERS] Delete a user',
    apiPath: '/api/v1/users/:id',
    method: 'DELETE',
    module: 'USERS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  // ROLES MODULE
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[ROLES] Create a new role',
    apiPath: '/api/v1/roles',
    method: 'POST',
    module: 'ROLES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[ROLES] Get all roles',
    apiPath: '/api/v1/roles',
    method: 'GET',
    module: 'ROLES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[ROLES] Get a role by id',
    apiPath: '/api/v1/roles/:id',
    method: 'GET',
    module: 'ROLES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[ROLES] Update a role',
    apiPath: '/api/v1/roles/:id',
    method: 'PATCH',
    module: 'ROLES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[ROLES] Delete a role',
    apiPath: '/api/v1/roles/:id',
    method: 'DELETE',
    module: 'ROLES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  // JOBS MODULE
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[JOBS] Create a new job',
    apiPath: '/api/v1/jobs',
    method: 'POST',
    module: 'JOBS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[JOBS] Get list job with pagination',
    apiPath: '/api/v1/jobs',
    method: 'GET',
    module: 'JOBS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[JOBS] Get a job by id',
    apiPath: '/api/v1/jobs/:id',
    method: 'GET',
    module: 'JOBS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[JOBS] Update a job',
    apiPath: '/api/v1/jobs/:id',
    method: 'PATCH',
    module: 'JOBS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[JOBS] Delete a job',
    apiPath: '/api/v1/jobs/:id',
    method: 'DELETE',
    module: 'JOBS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  // FILES MODULE
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[FILES] Upload file',
    apiPath: '/api/v1/files/upload',
    method: 'POST',
    module: 'FILES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[FILES] Get all files',
    apiPath: '/api/v1/files',
    method: 'GET',
    module: 'FILES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[FILES] Get a file by id',
    apiPath: '/api/v1/files/:id',
    method: 'GET',
    module: 'FILES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[FILES] Update a file',
    apiPath: '/api/v1/files/:id',
    method: 'PATCH',
    module: 'FILES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[FILES] Delete a file',
    apiPath: '/api/v1/files/:id',
    method: 'DELETE',
    module: 'FILES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  // RESUMES MODULE
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[RESUMES] Create a new resume',
    apiPath: '/api/v1/resumes',
    method: 'POST',
    module: 'RESUMES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[RESUMES] Get resume by user',
    apiPath: '/api/v1/resumes/by-user',
    method: 'POST',
    module: 'RESUMES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[RESUMES] Get all resumes',
    apiPath: '/api/v1/resumes',
    method: 'GET',
    module: 'RESUMES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[RESUMES] Get a resume by id',
    apiPath: '/api/v1/resumes/:id',
    method: 'GET',
    module: 'RESUMES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[RESUMES] Update status resume',
    apiPath: '/api/v1/resumes/:id',
    method: 'PATCH',
    module: 'RESUMES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[RESUMES] Delete a resume',
    apiPath: '/api/v1/resumes/:id',
    method: 'DELETE',
    module: 'RESUMES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  // SUBSCRIBERS MODULE
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[SUBSCRIBERS] Create a new subscriber',
    apiPath: '/api/v1/subscribers',
    method: 'POST',
    module: 'SUBSCRIBERS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[SUBSCRIBERS] Get all subscribers',
    apiPath: '/api/v1/subscribers',
    method: 'GET',
    module: 'SUBSCRIBERS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[SUBSCRIBERS] Get a subscriber by id',
    apiPath: '/api/v1/subscribers/:id',
    method: 'GET',
    module: 'SUBSCRIBERS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[SUBSCRIBERS] Update a subscriber',
    apiPath: '/api/v1/subscribers/:id',
    method: 'PATCH',
    module: 'SUBSCRIBERS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[SUBSCRIBERS] Delete a subscriber',
    apiPath: '/api/v1/subscribers/:id',
    method: 'DELETE',
    module: 'SUBSCRIBERS',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  // AUTH MODULE
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[AUTH] User login',
    apiPath: '/api/v1/auth/login',
    method: 'POST',
    module: 'AUTH',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[AUTH] Register a new user',
    apiPath: '/api/v1/auth/register',
    method: 'POST',
    module: 'AUTH',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[AUTH] Get user information',
    apiPath: '/api/v1/auth/account',
    method: 'GET',
    module: 'AUTH',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[AUTH] Get user by refresh token',
    apiPath: '/api/v1/auth/refresh',
    method: 'GET',
    module: 'AUTH',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[AUTH] Logout User',
    apiPath: '/api/v1/auth/logout',
    method: 'POST',
    module: 'AUTH',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
  // DATABASES MODULE
  {
    _id: new mongoose.Types.ObjectId(),
    name: '[DATABASES] Sync permissions successfully',
    apiPath: '/api/v1/databases/sync-permissions',
    method: 'POST',
    module: 'DATABASES',
    createdBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    isDeleted: false,
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
    updatedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
    deletedBy: {
      _id: new mongoose.Types.ObjectId(),
      email: 'superadmin@gmail.com',
    },
  },
];
